# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 04:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.CharField(default='not sure', max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profilepic/')),
                ('about_me', models.TextField(blank=True, max_length=150)),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
